spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: { 데이터베이스 이름 }
    password: { 비번 }

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true
    # data.sql 사용 시 스키마 생성 후 실행되게
    defer-datasource-initialization: true

  sql:
    init:
      # data.sql 항상 실행
      mode: always

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        same-site: None
        secure: false

app:
  cors:
    allowed-origins:
      - http://localhost:3000

# ====== 여기 두 줄이 OPENAI/GCP Key 미설정으로 나는 부팅 실패를 막음 ======
OPENAI_API_KEY: dummy
GCP_API_KEY: dummy
# (코드가 @Value("${OPENAI_API_KEY}") 등을 직접 읽으면 위 키가 필요)

openai:
  api:
    key: ${OPENAI_API_KEY}
gcp:
  api:
    key: ${GCP_API_KEY}
