spring:
  application:
    name: backend-project
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/backend # 테이블 이름
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME} # .env에 등록된 username
    password: ${DB_PASSWORD} # .env에 등록된 password

  jpa:
    hibernate:
      ddl-auto: create  # 초기에는 create, 배포 전 update로 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: true

data:
  init: true

app:
  cors:
    allowed-origins:
      - http://localhost:3000   # FE 로컬 주소

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        same-site: None
        secure: false           # 로컬(http)에서는 false, 배포 시 true로 변경

openai:
  api:
    key: ${OPENAI_API_KEY}

gcp:
  api:
    key: ${GCP_API_KEY}

