spring:
  application:
    name: backend-project

  datasource:
    url: jdbc:mysql://localhost:3306/backend #테이블 이름
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME} #자기 username .env에 등록
    password: ${DB_PASSWORD} # 자기 password .env에 등록

  jpa:
    hibernate:
      ddl-auto: create  # 초기에는 create, 나중에 배포 전에 update로 바꿔주기!
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: false

data:
  init: true

gcp:
  api:
    key: ${GCP_API_KEY}